=== pnnl/ConStrain/constrain/schema/workflow.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "workflow_name": {
            "type": "string"
        },
        "meta": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "date": {
                    "type": "string",
                    "pattern": "^\\d{2}\/\\d{2}\/\\d{4}$"
                },
                "version": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "author",
                "date",
                "version",
                "description"
            ],
            "additionalProperties": false
        },
        "imports": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "working_dir": {
            "type": "string"
        },
        "states": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/$defs/state"
            },
            "minProperties": 1
        }
    },
    "required": [
        "workflow_name",
        "meta",
        "imports",
        "states"
    ],
    "additionalProperties": false,
    "$defs": {
        "flagString": {
            "enum": [
                "True",
                "False"
            ]
        },
        "jsonValue": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "type": "number"
                },
                {
                    "type": "boolean"
                },
                {
                    "type": "null"
                },
                {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/jsonValue"
                    }
                },
                {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/$defs/jsonValue"
                    }
                }
            ]
        },
        "embeddedMethodCall": {
            "type": "object",
            "properties": {
                "Type": {
                    "const": "Embedded MethodCall"
                },
                "MethodCall": {
                    "type": "string"
                },
                "Parameters": {
                    "$ref": "#/$defs/parameters"
                }
            },
            "required": [
                "Type",
                "MethodCall",
                "Parameters"
            ],
            "additionalProperties": false
        },
        "parameterValue": {
            "anyOf": [
                {
                    "$ref": "#/$defs/jsonValue"
                },
                {
                    "$ref": "#/$defs/embeddedMethodCall"
                }
            ]
        },
        "parameters": {
            "oneOf": [
                {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/$defs/parameterValue"
                    }
                },
                {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/parameterValue"
                    }
                }
            ]
        },
        "payloads": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/$defs/jsonValue"
            }
        },
        "choicePredicate": {
            "type": "object",
            "properties": {
                "Value": {
                    "anyOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "number"
                        },
                        {
                            "type": "boolean"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "Equals": {
                    "anyOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "number"
                        },
                        {
                            "type": "boolean"
                        },
                        {
                            "type": "null"
                        }
                    ]
                },
                "Next": {
                    "type": "string"
                }
            },
            "required": [
                "Value",
                "Equals",
                "Next"
            ],
            "additionalProperties": false
        },
        "logicalAllChoice": {
            "type": "object",
            "properties": {
                "ALL": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/choicePredicate"
                    },
                    "minItems": 1
                },
                "AND": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/choicePredicate"
                    },
                    "minItems": 1
                },
                "Next": {
                    "type": "string"
                }
            },
            "required": [
                "Next"
            ],
            "oneOf": [
                {
                    "required": [
                        "ALL"
                    ]
                },
                {
                    "required": [
                        "AND"
                    ]
                }
            ],
            "additionalProperties": false
        },
        "logicalAnyChoice": {
            "type": "object",
            "properties": {
                "ANY": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/choicePredicate"
                    },
                    "minItems": 1
                },
                "Next": {
                    "type": "string"
                }
            },
            "required": [
                "ANY",
                "Next"
            ],
            "additionalProperties": false
        },
        "logicalNoneChoice": {
            "type": "object",
            "properties": {
                "NONE": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/choicePredicate"
                    },
                    "minItems": 1
                },
                "Next": {
                    "type": "string"
                }
            },
            "required": [
                "NONE",
                "Next"
            ],
            "additionalProperties": false
        },
        "state": {
            "oneOf": [
                {
                    "type": "object",
                    "properties": {
                        "Type": {
                            "const": "MethodCall"
                        },
                        "MethodCall": {
                            "type": "string"
                        },
                        "Parameters": {
                            "$ref": "#/$defs/parameters"
                        },
                        "Payloads": {
                            "$ref": "#/$defs/payloads"
                        },
                        "Next": {
                            "type": "string"
                        },
                        "Start": {
                            "$ref": "#/$defs/flagString"
                        },
                        "End": {
                            "$ref": "#/$defs/flagString"
                        }
                    },
                    "required": [
                        "Type",
                        "MethodCall",
                        "Parameters"
                    ],
                    "allOf": [
                        {
                            "if": {
                                "properties": {
                                    "End": {
                                        "const": "True"
                                    }
                                },
                                "required": [
                                    "End"
                                ]
                            },
                            "then": true,
                            "else": {
                                "required": [
                                    "Next"
                                ]
                            }
                        }
                    ],
                    "additionalProperties": false
                },
                {
                    "type": "object",
                    "properties": {
                        "Type": {
                            "const": "Choice"
                        },
                        "Choices": {
                            "type": "array",
                            "items": {
                                "$ref": "#/$defs/choice"
                            },
                            "minItems": 1
                        },
                        "Default": {
                            "type": "string"
                        },
                        "Start": {
                            "$ref": "#/$defs/flagString"
                        },
                        "End": {
                            "$ref": "#/$defs/flagString"
                        }
                    },
                    "required": [
                        "Type",
                        "Choices",
                        "Default"
                    ],
                    "additionalProperties": false
                }
            ]
        },
        "choice": {
            "oneOf": [
                {
                    "$ref": "#/$defs/choicePredicate"
                },
                {
                    "$ref": "#/$defs/logicalAllChoice"
                },
                {
                    "$ref": "#/$defs/logicalAnyChoice"
                },
                {
                    "$ref": "#/$defs/logicalNoneChoice"
                }
            ]
        }
    }
}

=== pnnl/ConStrain/constrain/os_measure/tests/test_files/G36_demo_workflow.json
{
  "workflow_name": "G36 Demo workflow",
  "working_dir": "/mnt/c/Users/slan572/repos/Constrain/",
  "meta": {
    "author": "ConStrain Team",
    "date": "06/29/2023",
    "version": "1.0",
    "description": "Demo workflow to showcase G36 verification item development"
  },
  "imports": [
    "numpy as np",
    "pandas as pd"
  ],
  "states": {
    "load data": {
      "Type": "MethodCall",
      "MethodCall": "DataProcessing",
      "Parameters": {
        "data_path": "./demo/G36_demo/data/G36_Modelica_Jan.csv",
        "data_source": "EnergyPlus"
      },
      "Payloads": {
        "data_processing_obj": "$",
        "data": "$.data"
      },
      "Start": "True",
      "Next": "load verification cases"
    },
    "load verification cases": {
      "Type": "MethodCall",
      "MethodCall": "VerificationCase",
      "Parameters": {
        "json_case_path": "./demo/G36_demo/data/G36_library_verification_cases.json"
      },
      "Payloads": {
        "verification_case_obj": "$",
        "original_case_keys": "$.case_suite.keys()"
      },
      "Next": "check original case length"
    },
    "check original case length": {
      "Type": "Choice",
      "Choices": [
        {
          "Value": "len(Payloads['original_case_keys']) == 3",
          "Equals": "True",
          "Next": "validate cases"
        }
      ],
      "Default": "Report Error in workflow"
    },
    "validate cases": {
      "Type": "Choice",
      "Choices": [
        {
          "Value": "Payloads['verification_case_obj'].validate()",
          "Equals": "True",
          "Next": "setup verification"
        }
      ],
      "Default": "Report Error in workflow"
    },
    "setup verification": {
      "Type": "MethodCall",
      "MethodCall": "Verification",
      "Parameters": {
        "verifications": "Payloads['verification_case_obj']"
      },
      "Payloads": {
        "verification_obj": "$"
      },
      "Next": "configure verification runner"
    },
    "configure verification runner": {
      "Type": "MethodCall",
      "MethodCall": "Payloads['verification_obj'].configure",
      "Parameters": {
        "output_path": "./demo/G36_demo",
        "lib_items_path": "./schema/library.json",
        "plot_option": "+x None",
        "fig_size": "+x (6, 5)",
        "num_threads": 1,
        "preprocessed_data": "Payloads['data']"
      },
      "Payloads": {},
      "Next": "run verification"
    },
    "run verification": {
      "Type": "MethodCall",
      "MethodCall": "Payloads['verification_obj'].run",
      "Parameters": {},
      "Payloads": {
        "verification_return": "$"
      },
      "Next": "check results"
    },
    "check results": {
      "Type": "MethodCall",
      "MethodCall": "glob.glob",
      "Parameters": [
        "./demo/G36_demo/*_md.json"
      ],
      "Payloads": {
        "length_of_mdjson": "len($)"
      },
      "Next": "check number of result files"
    },
    "check number of result files": {
      "Type": "Choice",
      "Choices": [
        {
          "Value": "Payloads['length_of_mdjson']",
          "Equals": "3",
          "Next": "reporting_object_instantiation"
        }
      ],
      "Default": "Report Error in workflow"
    },
    "reporting_object_instantiation": {
      "Type": "MethodCall",
      "MethodCall": "Reporting",
      "Parameters": {
        "verification_json": "./demo/G36_demo/*_md.json",
        "result_md_name": "report_summary.md",
        "report_format": "markdown"
      },
      "Payloads": {
        "reporting_obj": "$"
      },
      "Next": "report_cases"
    },
    "report_cases": {
      "Type": "MethodCall",
      "MethodCall": "Payloads['reporting_obj'].report_multiple_cases",
      "Parameters": {},
      "Payloads": {},
      "Next": "Success"
    },
    "Success": {
      "Type": "MethodCall",
      "MethodCall": "print",
      "Parameters": [
        "Congratulations! the demo workflow is executed with expected results and no error!"
      ],
      "End": "True"
    },
    "Report Error in workflow": {
      "Type": "MethodCall",
      "MethodCall": "logging.error",
      "Parameters": [
        "Something is wrong in the workflow execution"
      ],
      "End": "True"
    }
  }
}
