=== pnnl/ConStrain/schema/workflow.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/pnnl/ConStrain/tree/develop/schema/Workflow",
    "type": "object",
    "properties": {
        "workflow_name": {
            "type": "string"
        },
        "meta": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "date": {
                    "type": "string",
                    "pattern": "^\\d{2}\/\\d{2}\/\\d{4}$"
                },
                "version": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "author",
                "date",
                "version",
                "description"
            ],
            "additionalProperties": false
        },
        "imports": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "states": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/$defs/state"
            },
            "minProperties": 1
        }
    },
    "required": [
        "workflow_name",
        "meta",
        "imports",
        "states"
    ],
    "additionalProperties": false,
    "$defs": {
        "state": {
            "type": "object",
            "properties": {
                "Type": {
                    "enum": ["MethodCall", "Choice"]
                },
                "MethodCall": {
                    "type": "string"
                },
                "Parameters": {
                    "oneOf": [
                        {
                            "type": "object"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ]
                },
                "Payloads": {
                    "type": "object"
                },
                "Choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/choice"
                    }
                },
                "Default": {
                    "type": "string"
                },
                "Next": {
                    "type": "string"
                },
                "Start": {
                    "enum": [
                        "True",
                        "False"
                    ]
                },
                "End": {
                    "enum": [
                        "True",
                        "False"
                    ]
                }
            },
            "required": [
                "Type"
            ],
            "if": {
                "properties": {
                    "Type": {
                        "const": "MethodCall"
                    }
                }
            },
            "then": {
                "required": [
                    "Parameters"
                ],
                "not": {
                    "anyOf": [
                        {
                            "required": [
                                "Choices"
                            ]
                        },
                        {
                            "required": [
                                "Default"
                            ]
                        }
                    ]
                }
            },
            "else": {
                "required": [
                    "Choices",
                    "Default"
                ],
                "not": {
                    "required": [
                        "Parameters"
                    ]
                }
            }
        },
        "choice": {
            "type": "object",
            "properties": {
                "Value": {
                    "type": "string"
                },
                "Equals": {
                    "type": "string"
                },
                "Next": {
                    "type": "string"
                }
            },
            "required": [
                "Value",
                "Equals",
                "Next"
            ]
        }
    }
}

=== pnnl/ConStrain/demo/hpwh_demo/hpwh_demo_workflow.json
{
    "workflow_name": "HPWH workflow",
    "meta": {
        "author": "Yun Joon Jung",
        "date": "08/26/2024",
        "version": "1.0",
        "description": "Demo workflow to showcase core Workflow API functionalities"
    },
    "imports": [
        "numpy as np",
        "pandas as pd",
        "glob"
    ],
    "states": {
		"load timeseries data": {
            "Type": "MethodCall",
            "MethodCall": "DataProcessing",
            "Parameters": {
                "data_path": "./demo/hpwh_demo/IECC-state-current-5B_ApartmentMidRise_STD2021_WA-Spokane-WA.csv",
                "data_source": "EnergyPlus"
            },
            "Payloads": {"data_processing_obj": "$", "data": "$.data"},
			"Start": "True",
            "Next": "load original verification case"
        },	
		"load original verification case": {
            "Type": "MethodCall",
            "MethodCall": "VerificationCase",
            "Parameters": {
                "json_case_path": "./demo/hpwh_demo/hpwh_demo_verification_cases.json"
            },
            "Payloads": {
                "verification_case_obj": "$",
                "original_case_keys": "$.case_suite.keys()"
            },
            "Next": "setup verification"
        },
		"setup verification": {
            "Type": "MethodCall",
            "MethodCall": "Verification",
            "Parameters": {"verifications": "Payloads['verification_case_obj']"},
            "Payloads": {"verification_obj": "$"},
            "Next": "configure verification runner"
        },
		"configure verification runner": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['verification_obj'].configure",
            "Parameters": {
                "output_path": "./demo/hpwh_demo/outputs",
                "lib_items_path": "./schema/library.json",
                "plot_option": "+x None",
                "fig_size": "+x (6, 5)",
                "num_threads": 1,
                "preprocessed_data": "Payloads['data']"
            },
            "Payloads": {},
            "Next": "run verification"
        },
		"run verification": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['verification_obj'].run",
            "Parameters": {},
            "Payloads": {"verification_return": "$"},
            "Next": "reporting_object_instantiation"
        },
        "reporting_object_instantiation": {
            "Type": "MethodCall",
            "MethodCall": "Reporting",
            "Parameters": {
                "verification_json": "./demo/hpwh_demo/outputs/*_md.json",
                "result_md_name": "report_summary.md",
                "report_format": "markdown"
            },
            "Payloads": {"reporting_obj": "$"},
            "Next": "report cases"
        },
        "report cases": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['reporting_obj'].report_multiple_cases",
            "Parameters": {},
            "Payloads": {},
            "Next": "Success"
        },
        "Success": {
            "Type": "MethodCall",
            "MethodCall": "print",
            "Parameters": [
                "Congratulations! the demo workflow is executed with expected results and no error!"
            ],
            "Payloads": {},
            "End": "True"
        }
    }
}
