=== pnnl/ConStrain/schema/workflow.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/pnnl/ConStrain/tree/develop/schema/Workflow",
    "type": "object",
    "properties": {
        "workflow_name": {
            "type": "string"
        },
        "meta": {
            "type": "object",
            "properties": {
                "author": {
                    "type": "string"
                },
                "date": {
                    "type": "string",
                    "pattern": "^\\d{2}\/\\d{2}\/\\d{4}$"
                },
                "version": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "author",
                "date",
                "version",
                "description"
            ],
            "additionalProperties": false
        },
        "imports": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "states": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/$defs/state"
            },
            "minProperties": 1
        }
    },
    "required": [
        "workflow_name",
        "meta",
        "imports",
        "states"
    ],
    "additionalProperties": false,
    "$defs": {
        "state": {
            "type": "object",
            "properties": {
                "Type": {
                    "enum": ["MethodCall", "Choice"]
                },
                "MethodCall": {
                    "type": "string"
                },
                "Parameters": {
                    "oneOf": [
                        {
                            "type": "object"
                        },
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    ]
                },
                "Payloads": {
                    "type": "object"
                },
                "Choices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/choice"
                    }
                },
                "Default": {
                    "type": "string"
                },
                "Next": {
                    "type": "string"
                },
                "Start": {
                    "enum": [
                        "True",
                        "False"
                    ]
                },
                "End": {
                    "enum": [
                        "True",
                        "False"
                    ]
                }
            },
            "required": [
                "Type"
            ],
            "if": {
                "properties": {
                    "Type": {
                        "const": "MethodCall"
                    }
                }
            },
            "then": {
                "required": [
                    "Parameters"
                ],
                "not": {
                    "anyOf": [
                        {
                            "required": [
                                "Choices"
                            ]
                        },
                        {
                            "required": [
                                "Default"
                            ]
                        }
                    ]
                }
            },
            "else": {
                "required": [
                    "Choices",
                    "Default"
                ],
                "not": {
                    "required": [
                        "Parameters"
                    ]
                }
            }
        },
        "choice": {
            "type": "object",
            "properties": {
                "Value": {
                    "type": "string"
                },
                "Equals": {
                    "type": "string"
                },
                "Next": {
                    "type": "string"
                }
            },
            "required": [
                "Value",
                "Equals",
                "Next"
            ]
        }
    }
}

=== pnnl/ConStrain/docker/examples/workflows/G36_demo_workflow.json
{
  "workflow_name": "G36 Demo workflow",
  "meta": {
    "author": "ConStrain Team",
    "date": "06/29/2023",
    "version": "1.0",
    "description": "Demo workflow to showcase G36 verification item development"
  },
  "imports": [
    "numpy as np",
    "pandas as pd"
  ],
  "states": {
    "load data": {
      "Type": "MethodCall",
      "MethodCall": "DataProcessing",
      "Parameters": {
        "data_path": "./data/G36_Modelica_Jan.csv",
        "data_source": "EnergyPlus"
      },
      "Payloads": {
        "data_processing_obj": "$",
        "data": "$.data"
      },
      "Start": "True",
      "Next": "load verification cases"
    },
    "load verification cases": {
      "Type": "MethodCall",
      "MethodCall": "VerificationCase",
      "Parameters": {
        "json_case_path": "./verification_cases/G36_library_verification_cases.json"
      },
      "Payloads": {
        "verification_case_obj": "$",
        "original_case_keys": "$.case_suite.keys()"
      },
      "Next": "check original case length"
    },
    "check original case length": {
      "Type": "Choice",
      "Choices": [
        {
          "Value": "len(Payloads['original_case_keys']) == 3",
          "Equals": "True",
          "Next": "validate cases"
        }
      ],
      "Default": "Report Error in workflow"
    },
    "validate cases": {
      "Type": "Choice",
      "Choices": [
        {
          "Value": "Payloads['verification_case_obj'].validate()",
          "Equals": "True",
          "Next": "setup verification"
        }
      ],
      "Default": "Report Error in workflow"
    },
    "setup verification": {
      "Type": "MethodCall",
      "MethodCall": "Verification",
      "Parameters": {
        "verifications": "Payloads['verification_case_obj']"
      },
      "Payloads": {
        "verification_obj": "$"
      },
      "Next": "configure verification runner"
    },
    "configure verification runner": {
      "Type": "MethodCall",
      "MethodCall": "Payloads['verification_obj'].configure",
      "Parameters": {
        "output_path": "./results",
        "lib_items_path": "./schema/library.json",
        "plot_option": "+x None",
        "fig_size": "+x (6, 5)",
        "num_threads": 1,
        "preprocessed_data": "Payloads['data']"
      },
      "Payloads": {},
      "Next": "run verification"
    },
    "run verification": {
      "Type": "MethodCall",
      "MethodCall": "Payloads['verification_obj'].run",
      "Parameters": {},
      "Payloads": {
        "verification_return": "$"
      },
      "Next": "check results"
    },
    "check results": {
      "Type": "MethodCall",
      "MethodCall": "glob.glob",
      "Parameters": [
        "./demo/G36_demo/*_md.json"
      ],
      "Payloads": {
        "length_of_mdjson": "len($)"
      },
      "Next": "check number of result files"
    },
    "check number of result files": {
      "Type": "Choice",
      "Choices": [
        {
          "Value": "Payloads['length_of_mdjson']",
          "Equals": "3",
          "Next": "reporting_object_instantiation"
        }
      ],
      "Default": "Report Error in workflow"
    },
    "reporting_object_instantiation": {
      "Type": "MethodCall",
      "MethodCall": "Reporting",
      "Parameters": {
        "verification_json": "./demo/G36_demo/*_md.json",
        "result_md_name": "report_summary.md",
        "report_format": "markdown"
      },
      "Payloads": {
        "reporting_obj": "$"
      },
      "Next": "report_cases"
    },
    "report_cases": {
      "Type": "MethodCall",
      "MethodCall": "Payloads['reporting_obj'].report_multiple_cases",
      "Parameters": {},
      "Payloads": {},
      "Next": "Success"
    },
    "Success": {
      "Type": "MethodCall",
      "MethodCall": "print",
      "Parameters": [
        "Congratulations! the demo workflow is executed with expected results and no error!"
      ],
      "End": "True"
    },
    "Report Error in workflow": {
      "Type": "MethodCall",
      "MethodCall": "logging.error",
      "Parameters": [
        "Something is wrong in the workflow execution"
      ],
      "End": "True"
    }
  }
}

=== pnnl/ConStrain/constrain/demo/brick/brick_workflow.json
{
    "workflow_name": "Brick workflow",
    "meta": {
        "author": "Constrain Team",
        "date": "08/21/2023",
        "version": "1.0",
        "description": "Demo workflow to showcase core brick API functionalities"
    },
    "imports": ["numpy as np", "pandas as pd", "datetime", "glob"],
    "states": {
        "instantiate BrickCompliance object": {
            "Type": "MethodCall",
            "MethodCall": "BrickCompliance",
            "Parameters": {
                "brick_schema_path": "../../../resources/brick/Brick.ttl",
                "brick_instance_path": "../../../resources/brick/brick_instance.ttl",
                "query_statement_path": "../../../resources/brick/query_statement.yml",
                "datapoint_name_conversion_path": "../../../resources/brick/verification_datapoint_info.yml"
            },
            "Payloads": {"BrickCompliance_obj": "$"},
            "Start": "True",
            "Next": "query datapoints"
        },
        "query datapoints": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['BrickCompliance_obj'].query_verification_case_datapoints",
            "Parameters": {
                "verification_item_lib_name": "ZoneTempControl",
                "energyplus_naming_assembly": false,
						    "default_verification_case_values": "{'run_simulation': False, 'simulation_IO': {'idf': 'EnergyPlus_data', 'idd': '', 'weather': '', 'output': './data/data_file.csv', 'ep_path': ''}, 'expected_result': 'pass', 'parameters': {}}"},
            "Payloads": {"query_result": "$"},
            "Next": "instantiate verification case"
			  },
        "instantiate verification case": {
            "Type": "MethodCall",
            "MethodCall": "VerificationCase",
            "Parameters": {},
            "Payloads": {"verification_case_obj": "$"},
            "Next": "save query result"
        },
        "save query result": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['verification_case_obj'].save_verification_cases_to_json",
            "Parameters": {
                "json_path": "./data/query_result.json",
                "cases": "Payloads['query_result']"
            },
            "Payloads": {},
            "Next": "load verification cases"
        },
        "load verification cases": {
            "Type": "MethodCall",
            "MethodCall": "VerificationCase",
            "Parameters": {
                "json_case_path": "./data/query_result.json"
            },
            "Payloads": {"verification_case_obj": "$"},
            "Next": "load timeseries data"
        },
        "load timeseries data": {
            "Type": "MethodCall",
            "MethodCall": "DataProcessing",
            "Parameters": {
                "data_path": "./data/data_file.csv",
                "data_source": "EnergyPlus"
            },
            "Payloads": {"data_processing_obj": "$", "data": "$.data"},
            "Next": "setup verification"
        },
        "setup verification": {
            "Type": "MethodCall",
            "MethodCall": "Verification",
            "Parameters": {"verifications": "Payloads['verification_case_obj']"},
            "Payloads": {"verification_obj": "$"},
            "Next": "configure verification runner"
        },
        "configure verification runner": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['verification_obj'].configure",
            "Parameters": {
                "output_path": "./data",
                "lib_items_path": "../../../constrain/schema/library.json",
                "plot_option": "+x None",
                "fig_size": "+x (6, 5)",
                "num_threads": 1,
                "preprocessed_data": "Payloads['data']"
            },
            "Payloads": {},
            "Next": "run verification"
        },
        "run verification": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['verification_obj'].run",
            "Parameters": {},
            "Payloads": {"verification_return": "$"},
            "Next": "reporting_object_instantiation"
        },
        "reporting_object_instantiation": {
            "Type": "MethodCall",
            "MethodCall": "Reporting",
            "Parameters": {
                "verification_json": "./data/*_md.json",
                "result_md_name": "report_summary.md",
                "report_format": "markdown"
            },
            "Payloads": {"reporting_obj": "$"},
            "Next": "report cases"
        },
        "report cases": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['reporting_obj'].report_multiple_cases",
            "Parameters": {},
            "Payloads": {},
            "Next": "Success"
        },
        "Success": {
            "Type": "MethodCall",
            "MethodCall": "print",
            "Parameters": [
                "Congratulations! the demo workflow is executed with expected results and no error!"
            ],
            "Payloads": {},
            "End": "True"
        }
    }
}

=== pnnl/ConStrain/tests/G36/G36_workflow.json
{
  "workflow_name": "G36 Demo workflow",
  "meta": {
    "author": "ConStrain Team",
    "date": "06/29/2023",
    "version": "1.0",
    "description": "Demo workflow to showcase G36 verification item development"
  },
  "imports": [
    "numpy as np",
    "pandas as pd"
  ],
  "states": {
    "Load G36_SupplyAirTemperatureSetpoint_data": {
      "Type": "MethodCall",
      "MethodCall": "DataProcessing",
      "Parameters": {
        "data_path": "./tests/G36/data/G36_SupplyAirTemperatureSetpoint.csv",
	"data_source": "EnergyPlus"
      },
      "Payloads": {
        "data_processing_SATSP_obj": "$"
      },
      "Start": "True",
      "Next": "Load_G36OutdoorAirDamperPositionForReliefDamperOrFan_data"
    },
    "Load_G36OutdoorAirDamperPositionForReliefDamperOrFan_data": {
      "Type": "MethodCall",
      "MethodCall": "DataProcessing",
      "Parameters": {
        "data_path": "./tests/G36/data/G36OutdoorAirDamperPositionForReliefDamperOrFan.csv",
	"data_source": "EnergyPlus"
      },
      "Payloads": {
        "data_processing_OADPRDF_obj": "$"
      },
      "Next": "Load_G36ReturnAirDamperPositionForReliefDamperOrFan_data"
    },
    "Load_G36ReturnAirDamperPositionForReliefDamperOrFan_data": {
      "Type": "MethodCall",
      "MethodCall": "DataProcessing",
      "Parameters": {
        "data_path": "./tests/G36/data/G36ReturnAirDamperPositionForReliefDamperOrFan.csv",
	"data_source": "EnergyPlus"
      },
      "Payloads": {
        "data_processing_RADPRDF_obj": "$"
      },
      "Next": "load_verification_case"
    },
    "load_verification_case": {
      "Type": "MethodCall",
      "MethodCall": "VerificationCase",
      "Parameters": {
        "json_case_path": "./tests/G36/data/G36_library_verification_cases.json"
      },
      "Payloads": {
        "verification_case_obj": "$"
      },
      "Next": "Run_verification"
    },
    "setup_verification": {
      "Type": "MethodCall",
      "MethodCall": "Verification",
      "Parameters": {
        "verifications": "Payloads['verification_case_obj']"
      },
      "Payloads": {
        "verification_obj": "$"
      },
      "Next": "configure_verification_runner"
    },
    "configure_verification_runner": {
      "Type": "MethodCall",
      "MethodCall": "Payloads['verification_obj'].configure",
      "Parameters": {
        "output_path": "./tests/G36",
        "lib_items_path": "./tests/G36/data/G36_library_verification_cases.json"
      },
      "Payloads": {},
      "Next": "Run_verification"
    },
    "Run_verification": {
      "Type": "MethodCall",
      "MethodCall": "Payloads['verification_obj'].run",
      "Parameters": {},
      "Payloads": {
        "verification_md": "$.md"
      },
      "Next": "reporting_object_instantiation"
    },
    "reporting_object_instantiation": {
      "Type": "MethodCall",
      "MethodCall": "Reporting",
      "Parameters": {
        "verification_json": "./tests/G36/*_md.json",
        "result_md_name": "report_summary.md",
        "report_format": "markdown"
      },
      "Payloads": {
        "reporting_obj": "$"
      },
      "Next": "report_cases"
    },
    "report_cases": {
      "Type": "MethodCall",
      "MethodCall": "Payloads['reporting_obj'].report_multiple_cases",
      "Parameters": {},
      "Payloads": {},
      "End": "True"
    }
  }
}

=== pnnl/ConStrain/constrain/demo/brick_demo/brick_workflow.json
{
    "workflow_name": "Brick workflow",
    "meta": {
        "author": "Constrain Team",
        "date": "08/21/2023",
        "version": "1.0",
        "description": "Demo workflow to showcase core brick API functionalities"
    },
    "imports": ["numpy as np", "pandas as pd", "datetime", "glob"],
    "states": {
        "instantiate BrickCompliance object": {
            "Type": "MethodCall",
            "MethodCall": "BrickCompliance",
            "Parameters": {
                "brick_schema_path": "./resources/brick/Brick.ttl",
                "brick_instance_path": "./resources/brick/brick_instance.ttl"
            },
            "Payloads": {"BrickCompliance_obj": "$"},
            "Start": "True",
            "Next": "query datapoints"
        },
        "query datapoints": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['BrickCompliance_obj'].query_verification_case_datapoints",
            "Parameters": {
                "verification_item_lib_name": "ZoneTempControl",
                "energyplus_naming_assembly": false,
						    "default_verification_case_values": "{'run_simulation': False, 'verification_properties': {'idf': 'EnergyPlus_data', 'idd': './resources/Energy+V9_0_1.idd', 'weather': './weather/USA_GA_Atlanta-Hartsfield.Jackson.Intl.AP.722190_TMY3.epw', 'output': './demo/brick_demo/brick_dataset/data_file.csv', 'ep_path': 'C:\\\\\\\\EnergyPlusV9-0-1\\\\\\\\energyplus.exe'}, 'expected_result': 'pass', 'parameters': {}}"},
            "Payloads": {"query_result": "$"},
            "Next": "instantiate verification case"
			  },
        "instantiate verification case": {
            "Type": "MethodCall",
            "MethodCall": "VerificationCase",
            "Parameters": {},
            "Payloads": {"verification_case_obj": "$"},
            "Next": "save query result"
        },
        "save query result": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['verification_case_obj'].save_verification_cases_to_json",
            "Parameters": {
                "json_path": "./demo/brick_demo/brick_dataset/query_result.json",
                "cases": "Payloads['query_result']"
            },
            "Payloads": {},
            "Next": "load verification cases"
        },
        "load verification cases": {
            "Type": "MethodCall",
            "MethodCall": "VerificationCase",
            "Parameters": {
                "json_case_path": "./demo/brick_demo/brick_dataset/query_result.json"
            },
            "Payloads": {"verification_case_obj": "$"},
            "Next": "load timeseries data"
        },
        "load timeseries data": {
            "Type": "MethodCall",
            "MethodCall": "DataProcessing",
            "Parameters": {
                "data_path": "./demo/brick_demo/brick_dataset/data_file.csv",
                "data_source": "EnergyPlus"
            },
            "Payloads": {"data_processing_obj": "$", "data": "$.data"},
            "Next": "setup verification"
        },
        "setup verification": {
            "Type": "MethodCall",
            "MethodCall": "Verification",
            "Parameters": {"verifications": "Payloads['verification_case_obj']"},
            "Payloads": {"verification_obj": "$"},
            "Next": "configure verification runner"
        },
        "configure verification runner": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['verification_obj'].configure",
            "Parameters": {
                "output_path": "./demo/brick_demo/brick_dataset",
                "lib_items_path": "./schema/library.json",
                "plot_option": "+x None",
                "fig_size": "+x (6, 5)",
                "num_threads": 1,
                "preprocessed_data": "Payloads['data']"
            },
            "Payloads": {},
            "Next": "run verification"
        },
        "run verification": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['verification_obj'].run",
            "Parameters": {},
            "Payloads": {"verification_return": "$"},
            "Next": "reporting_object_instantiation"
        },
        "reporting_object_instantiation": {
            "Type": "MethodCall",
            "MethodCall": "Reporting",
            "Parameters": {
                "verification_json": "./demo/brick_demo/brick_dataset/*_md.json",
                "result_md_name": "report_summary.md",
                "report_format": "markdown"
            },
            "Payloads": {"reporting_obj": "$"},
            "Next": "report cases"
        },
        "report cases": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['reporting_obj'].report_multiple_cases",
            "Parameters": {},
            "Payloads": {},
            "Next": "Success"
        },
        "Success": {
            "Type": "MethodCall",
            "MethodCall": "print",
            "Parameters": [
                "Congratulations! the demo workflow is executed with expected results and no error!"
            ],
            "Payloads": {},
            "End": "True"
        }
    }
}

=== pnnl/ConStrain/examples/api_demo/demo_workflow.json
{
    "workflow_name": "Demo workflow",
    "meta": {
        "author": "Xuechen (Jerry) Lei",
        "date": "03/15/2023",
        "version": "1.0",
        "description": "Demo workflow to showcase core Workflow API functionalities"
    },
    "imports": [
        "numpy as np",
        "pandas as pd",
        "datetime",
        "glob"
    ],
    "states": {
        "load data": {
            "Type": "MethodCall",
            "MethodCall": "DataProcessing",
            "Parameters": {
                "data_path": "./examples/api_demo/demo_dataset.csv",
                "data_source": "EnergyPlus"
            },
            "Payloads": {
                "data_processing_obj": "$"
            },
            "Start": "True",
            "Next": "slice data to get the first two months"
        },
        "slice data to get the first two months": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['data_processing_obj'].slice",
            "Parameters": {
                "start_time": {
                    "Type": "Embedded MethodCall",
                    "MethodCall": "datetime.datetime",
                    "Parameters": [
                        2000,
                        1,
                        1,
                        0
                    ]
                },
                "end_time": {
                    "Type": "Embedded MethodCall",
                    "MethodCall": "datetime.datetime",
                    "Parameters": [
                        2000,
                        3,
                        1,
                        0
                    ]
                }
            },
            "Payloads": {
                "sliced_data": "$"
            },
            "Next": "load original verification case"
        },
        "load original verification case": {
            "Type": "MethodCall",
            "MethodCall": "VerificationCase",
            "Parameters": {
                "json_case_path": "./examples/api_demo/demo_verification_cases.json"
            },
            "Payloads": {
                "verification_case_obj": "$",
                "original_case_keys": "$.case_suite.keys()"
            },
            "Next": "check original case length"
        },
        "check original case length": {
            "Type": "Choice",
            "Choices": [
                {
                    "Value": "len(Payloads['original_case_keys']) == 3",
                    "Equals": "True",
                    "Next": "validate cases"
                }
            ],
            "Default": "Report Error in workflow"
        },
        "validate cases": {
            "Type": "Choice",
            "Choices": [
                {
                    "Value": "Payloads['verification_case_obj'].validate()",
                    "Equals": "True",
                    "Next": "setup verification"
                }
            ],
            "Default": "Report Error in workflow"
        },
        "setup verification": {
            "Type": "MethodCall",
            "MethodCall": "Verification",
            "Parameters": {
                "verifications": "Payloads['verification_case_obj']"
            },
            "Payloads": {
                "verification_obj": "$"
            },
            "Next": "configure verification runner"
        },
        "configure verification runner": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['verification_obj'].configure",
            "Parameters": {
                "output_path": "./examples/api_demo",
                "lib_items_path": "./schema/library.json",
                "plot_option": "+x None",
                "fig_size": "+x (6, 5)",
                "num_threads": 1,
                "preprocessed_data": "Payloads['sliced_data']"
            },
            "Payloads": {},
            "Next": "run verification"
        },
        "run verification": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['verification_obj'].run",
            "Parameters": {},
            "Payloads": {"verification_return": "$"},
            "Next": "check results"
        },
        "check results": {
            "Type": "MethodCall",
            "MethodCall": "glob.glob",
            "Parameters": [
                "./examples/api_demo/*_md.json"
            ],
            "Payloads": {
                "length_of_mdjson": "len($)"
            },
            "Next": "check number of result files"
        },
        "check number of result files": {
            "Type": "Choice",
            "Choices": [
                {
                    "Value": "Payloads['length_of_mdjson']",
                    "Equals": "3",
                    "Next": "reporting_object_instantiation"
                }
            ],
            "Default": "Report Error in workflow"
        },
        "reporting_object_instantiation": {
            "Type": "MethodCall",
            "MethodCall": "Reporting",
            "Parameters": {
                "verification_json": "./examples/api_demo/*_md.json",
                "result_md_name": "report_summary.md",
                "report_format": "markdown"
            },
            "Payloads": {
                "reporting_obj": "$"
            },
            "Next": "report_cases"
        },
        "report_cases": {
            "Type": "MethodCall",
            "MethodCall": "Payloads['reporting_obj'].report_multiple_cases",
            "Parameters": {},
            "Payloads": {},
            "Next": "Success"
        },
        "Success": {
            "Type": "MethodCall",
            "MethodCall": "print",
            "Parameters": [
                "Congratulations! the demo workflow is executed with expected results and no error!"
            ],
            "End": "True"
        },
        "Report Error in workflow": {
            "Type": "MethodCall",
            "MethodCall": "logging.error",
            "Parameters": [
                "Something is wrong in the workflow execution"
            ],
            "End": "True"
        }
    }
}
